name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
        command:
          - --tls=false

    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Docker to be ready
        run: |
          timeout 30 sh -c "until docker info; do sleep 1; done"

      - name: Write .env file
        run: |
          echo DATABASE_URL="${{ secrets.DATABASE_URL }}" > .env
          echo ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" >> .env

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
